Server:
  Port: 8081

Cache:
  CacheType: disk
  Port: 9425
  TTL: 0
  CacheDir: /home/eintr/Share/rocksdb

Database:
  Host: 192.168.23.169
  Port: 3306
  User: root
  Password: 123456789
  DBname: BigData
